on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

env:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    TZ: UTC
    NOT_CRAN: true
    GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
    GITHUB_PAT: ${{ secrets.GHTOKEN }}
      
jobs:
  R-CMD-check:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck","BiocManager","devtools"))
          message(paste('****', Sys.time(), 'pass number 1 at installing dependencies: local dependencies ****'))
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]])
          message(paste('****', Sys.time(), 'pass number 2 at installing dependencies: any remaining dependencies ****'))
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(deps$package[deps$diff != 0])
          message(paste('****', Sys.time(), 'installing rcmdcheck and BiocCheck ****'))
          remotes::install_cran("rcmdcheck")
          BiocManager::install("BiocCheck")
          remotes::install_cran("pkgdown")
        shell: Rscript {0}
      - name: Install CondaSys dependencies
        run: |
          devtools::install_github("RockefellerUniversity/CondaSysReqs",upgrade = "never")
          devtools::install_github("RockefellerUniversity/clipR")
          CondaSysReqs::install_CondaSysReqs("clipR")
          clipR::install_ctk()
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Make homepage
        run: |
          rmarkdown::render("README.Rmd")
        shell: Rscript {0}
      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
